---
- name: Install dependent packages
  become: yes
  package:
    name: "{{ magicmirror_apt_packages }}"
    state: present
  when: magicmirror_apt_packages is defined

- name: Create {{ magicmirror_src_dir }} directory
  file:
    path: "{{ magicmirror_src_dir }}"
    state: directory

- name: Create {{ magicmirror_src_dir }}/pm2 directory
  file:
    path: "{{ magicmirror_src_dir }}/MagicMirror_pm2"
    state: directory

- name: Check nodejs version
  shell: echo `nodejs -v` "{{ magicmirror_min_nodejs_version }}" | tr " " "\n" | sort -V | head -n 1
  register: nodejs_version
  changed_when: false

- name: Check if nodejs upgrade required
  set_fact: magicmirror_nodejs_upgrade_needed=yes
  when: nodejs_version.stdout is defined and nodejs_version.stdout != magicmirror_min_nodejs_version

- name: Upgrade nodejs
  block:
    - name: Check if any nodejs processes are running
      shell: pgrep nodejs > /dev/null 2>&1
      register: pgrep_nodejs
      failed_when: pgrep_nodejs.rc >= 2
      changed_when: false

    - name: Stop all nodejs processes
      command: killall nodejs -q
      when: pgrep_nodejs.rc == 0

    - name: Setup nodejs apt repository
      shell: curl -sL https://deb.nodesource.com/setup_{{ magicmirror_nodejs_stable_branch }} | bash -
      args:
        creates: /etc/apt/sources.list.d/nodesource.list
      register: apt_repository

    - name: Upgrade nodejs package
      apt:
        name: nodejs
        state: latest

  when: magicmirror_nodejs_upgrade_needed
  become: yes

- name: Clone MagicMirror repository
  git:
    repo: https://github.com/MagicMirrorOrg/MagicMirror.git
    dest: "{{ magicmirror_src_dir }}/MagicMirror"
    depth: 1
    update: no
    ssh_opts: -o StrictHostKeyChecking=no
    accept_hostkey: yes
  register: magicmirror_git

- name: Install MagicMirror npm dependencies
  command: npm install
  args:
    chdir: "{{ magicmirror_src_dir }}/MagicMirror"
  when: magicmirror_git.changed
