---
- name: Restart {{ magicmirror_watchdog_pm2_app }}
  listen: "restart mm"
  command: pm2 restart {{ magicmirror_watchdog_pm2_app }}

- name: reboot no wait
  become: yes
  shell: "sleep 1 && shutdown -r now +1"
  async: 1
  poll: 0
